import * as fse from 'fs-extra';
import * as os from 'os';
import * as path from 'path';

/**
 * Nothing a user pastes into another application may contain a value this
 * extension versions. VS Code puts the version in its extension directory
 * names, so a bridge path inside ours would break on every update - silently,
 * in an app that is not this one.
 *
 * Both the bridge and the file describing how to reach the server therefore
 * live at a fixed path, refreshed on activation.
 */
export function homeDir(): string {
  // Overridable so the bridge can be exercised against a throwaway directory,
  // and so an unusual setup can move it.
  return process.env.VSCODE_SFTP_HOME || path.join(os.homedir(), '.vscode-sftp');
}

export const discoveryPath = () => path.join(homeDir(), 'mcp.json');
export const bridgePath = () => path.join(homeDir(), 'mcp-bridge.js');

export interface Discovery {
  port: number;
  token: string;
  /** Which window is currently leader, for the status surface. */
  workspace?: string;
  pid: number;
  version: number;
}

export const DISCOVERY_VERSION = 1;

/**
 * Written 0600: a process running as this user could read it, but so could it
 * read the SSH keys next to it. What the token defends against is a web page
 * reaching loopback, and a page cannot read files.
 */
export async function writeDiscovery(
  discovery: Omit<Discovery, 'version'>
): Promise<void> {
  await fse.ensureDir(homeDir());
  const file = discoveryPath();

  await fse.writeFile(
    file,
    JSON.stringify({ ...discovery, version: DISCOVERY_VERSION }, null, 2),
    { encoding: 'utf8', mode: 0o600 }
  );
  // ensure the mode even when the file already existed
  await fse.chmod(file, 0o600);
}

export async function clearDiscovery(): Promise<void> {
  try {
    await fse.unlink(discoveryPath());
  } catch (error) {
    // Never existed, or somebody else cleaned up. Either is fine.
  }
}

export async function installBridge(): Promise<string> {
  await fse.ensureDir(homeDir());
  const file = bridgePath();

  // Rewritten every activation so an updated extension ships an updated bridge
  // without the user touching their client configuration.
  await fse.writeFile(file, BRIDGE_SOURCE, { encoding: 'utf8', mode: 0o700 });
  return file;
}

/** The snippet a user pastes into a stdio client. Carries no secret and no port. */
export function clientSnippet(): string {
  return JSON.stringify(
    {
      mcpServers: {
        sftp: { command: 'node', args: [bridgePath()] },
      },
    },
    null,
    2
  );
}

/**
 * Forwards newline-delimited JSON-RPC on stdio to the loopback endpoint, which
 * is how a client that only speaks stdio reaches an HTTP server.
 *
 * Written to disk rather than bundled so its path never changes.
 */
const BRIDGE_SOURCE = `#!/usr/bin/env node
'use strict';

// Generated by the SFTP extension. Edits will be overwritten.

const fs = require('fs');
const http = require('http');
const os = require('os');
const path = require('path');

const HOME = process.env.VSCODE_SFTP_HOME || path.join(os.homedir(), '.vscode-sftp');
const DISCOVERY = path.join(HOME, 'mcp.json');

function die(message) {
  process.stderr.write(message + '\\n');
  process.exit(1);
}

let discovery;
try {
  discovery = JSON.parse(fs.readFileSync(DISCOVERY, 'utf8'));
} catch (error) {
  die(
    'Cannot reach the SFTP MCP server: no connection details at ' + DISCOVERY + '.\\n' +
    'Open VS Code with the SFTP extension and set "sftp.mcp.enabled" to true.'
  );
}

if (!discovery || !discovery.port || !discovery.token) {
  die('The SFTP MCP connection details at ' + DISCOVERY + ' are incomplete.');
}

function send(body) {
  return new Promise(function (resolve, reject) {
    const payload = Buffer.from(body, 'utf8');
    const req = http.request(
      {
        host: '127.0.0.1',
        port: discovery.port,
        method: 'POST',
        path: '/',
        headers: {
          'Content-Type': 'application/json',
          'Content-Length': payload.length,
          Authorization: 'Bearer ' + discovery.token,
        },
      },
      function (res) {
        let text = '';
        res.on('data', function (chunk) { text += chunk; });
        res.on('end', function () { resolve({ status: res.statusCode, body: text }); });
      }
    );
    req.on('error', reject);
    req.end(payload);
  });
}

let buffer = '';
let queue = Promise.resolve();

process.stdin.setEncoding('utf8');
process.stdin.on('data', function (chunk) {
  buffer += chunk;

  let index;
  while ((index = buffer.indexOf('\\n')) !== -1) {
    const line = buffer.slice(0, index).trim();
    buffer = buffer.slice(index + 1);
    if (line === '') continue;

    queue = queue.then(function () {
      return send(line).then(
        function (response) {
          // 202 means the message was a notification; there is nothing to say.
          if (response.status === 202 || response.body === '') return;
          process.stdout.write(response.body.replace(/\\n/g, ' ') + '\\n');
        },
        function (error) {
          die('The SFTP MCP server stopped answering: ' + error.message);
        }
      );
    });
  }
});

// stdin closing does not mean the work is done: replies still in flight would
// be lost if the process left immediately.
process.stdin.on('end', function () {
  queue.then(function () { process.exit(0); });
});
`;

export { BRIDGE_SOURCE };
